image: Visual Studio 2017
platform: x64
configuration: OptimizedDebug
clone_folder: C:\Projects\bsf

environment:
  FTP_USER:
    secure: 6/QO2m0slpHVIaSvCgshSQ==
  FTP_PASSWORD:
    secure: NZnU8rVuQ/CeRYWBRObDfQ==
  FTP_HOST:
    secure: vkR/qaZuHZ7k7iZQBfLlNYJzx/+rzkhRlOloJq7o0mk=

build_script:
  - cmd: set INSTALL_DIR=C:/Projects/bsf/CI
  - cmd: mkdir "%INSTALL_DIR%"
  - cmd: mkdir Build
  - cmd: cd Build
  - cmd: cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX:STRING=%INSTALL_DIR% ..
  - cmd: cmake --build ./ --config OptimizedDebug
  - cmd: cmake --build ./ --config OptimizedDebug --target INSTALL

after_build:
 - cmd: 7z a bsfBinaries.zip ../CI/* -xr!*pdb
 - cmd: 7z a bsfSymbols.zip ../CI/*pdb -r

artifacts:
  - path: bsfBinaries.zip
    name: bsf_Win64_$(APPVEYOR_BUILD_NUMBER)
    type: zip
  - path: bsfSymbols.zip
    name: bsf_Win64_Symbols_$(APPVEYOR_BUILD_NUMBER)
    type: zip

deploy:
  - provider: FTP
    protocol: ftp
    host: $(FTP_HOST)
    username: $(FTP_USER)
    password: $(FTP_PASSWORD)
    folder: bsfBuilds
    application:
    active_mode: false
    beta: true
    debug: true
